-- ============================================================
-- 01_company.sql
-- Correr conectado como CONTA_SCHEMA en XEPDB1
-- Tabla raíz: toda tabla transaccional cuelga de COMPANY.
-- ============================================================

CREATE TABLE company (
    id                          NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                                 CONSTRAINT pk_company PRIMARY KEY,
    name                        VARCHAR2(150)   NOT NULL,
    tax_registration_number    VARCHAR2(20),    -- NRC: Número de Registro de Contribuyente (El Salvador)
    tax_id                      VARCHAR2(20),    -- NIT: Número de Identificación Tributaria (El Salvador)
    business_line               VARCHAR2(150),   -- giro comercial de la empresa
    is_active                   CHAR(1)         DEFAULT 'Y' NOT NULL
                                                 CONSTRAINT ck_company_active CHECK (is_active IN ('Y','N')),
    created_at                  DATE            DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE company IS 'Empresas configuradas en el sistema (multi-tenant por company_id)';
COMMENT ON COLUMN company.tax_registration_number IS 'NRC salvadoreño: Número de Registro de Contribuyente';
COMMENT ON COLUMN company.tax_id IS 'NIT salvadoreño: Número de Identificación Tributaria';
