-- ============================================================
-- 06_gl_account.sql
-- Depende de: 01_company.sql
-- Catálogo de cuentas jerárquico (padre-subcuenta) por empresa.
-- "GL" = General Ledger (Libro Mayor). Se llama gl_account y no
-- account para no confundirla con user_account.
-- is_posting_account='Y' es la regla clave: solo esas cuentas
-- admiten movimientos directos (nunca se contabiliza en una
-- cuenta padre/de agrupación).
-- ============================================================

CREATE TABLE gl_account (
    id                  NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         CONSTRAINT pk_gl_account PRIMARY KEY,
    company_id          NUMBER          NOT NULL
                                         CONSTRAINT fk_account_company
                                         REFERENCES company(id),
    parent_account_id   NUMBER
                                         CONSTRAINT fk_account_parent
                                         REFERENCES gl_account(id),
    code                VARCHAR2(20)    NOT NULL,   -- ej. '1101', '1101.01'
    name                VARCHAR2(150)   NOT NULL,
    normal_balance      CHAR(1)         NOT NULL
                                         CONSTRAINT ck_account_normal_balance
                                         CHECK (normal_balance IN ('D','C')),  -- D=Debit(Deudora), C=Credit(Acreedora)
    account_type        VARCHAR2(20)    NOT NULL
                                         CONSTRAINT ck_account_type
                                         CHECK (account_type IN ('ASSET','LIABILITY','EQUITY',
                                                                  'REVENUE','COST','EXPENSE')),
    is_posting_account  CHAR(1)         DEFAULT 'Y' NOT NULL
                                         CONSTRAINT ck_account_posting CHECK (is_posting_account IN ('Y','N')),
    is_active           CHAR(1)         DEFAULT 'Y' NOT NULL
                                         CONSTRAINT ck_account_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT uq_account_company_code UNIQUE (company_id, code)
);

COMMENT ON TABLE gl_account IS 'Catálogo de cuentas jerárquico por empresa (Libro Mayor)';
COMMENT ON COLUMN gl_account.normal_balance IS 'D=Deudora (Activo/Costo/Gasto), C=Acreedora (Pasivo/Patrimonio/Ingreso)';
COMMENT ON COLUMN gl_account.is_posting_account IS 'Solo Y admite movimientos directos; las cuentas padre (N) son de agrupación';
