-- ============================================================
-- 08_journal_entry_line.sql
-- Depende de: 07_journal_entry.sql, 06_gl_account.sql
-- Líneas del asiento. El cuadre (SUMA debe = SUMA haber) y la
-- regla de "solo cuentas de detalle" las valida el paquete
-- PL/SQL antes de insertar, no un CHECK de tabla (porque son
-- reglas que dependen de MÚLTIPLES filas / de otra tabla).
-- ============================================================

CREATE TABLE journal_entry_line (
    id                  NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         CONSTRAINT pk_entry_line PRIMARY KEY,
    journal_entry_id    NUMBER          NOT NULL
                                         CONSTRAINT fk_line_entry
                                         REFERENCES journal_entry(id),
    account_id          NUMBER          NOT NULL
                                         CONSTRAINT fk_line_account
                                         REFERENCES gl_account(id),
    movement_type       CHAR(1)         NOT NULL
                                         CONSTRAINT ck_line_movement_type
                                         CHECK (movement_type IN ('D','C')),  -- D=Debit, C=Credit
    amount              NUMBER(14,2)    NOT NULL
                                         CONSTRAINT ck_line_amount CHECK (amount > 0),
    description         VARCHAR2(300)
);

COMMENT ON TABLE journal_entry_line IS 'Líneas debe/haber de cada asiento (base de la mayorización)';
COMMENT ON COLUMN journal_entry_line.movement_type IS 'D=Debe (Debit), C=Haber (Credit)';
