-- ============================================================
-- 14_inventory_movement.sql
-- Depende de: 13_inventory_item.sql, 07_journal_entry.sql (opcional)
-- Cada fila es una línea de Kardex: una entrada o salida física
-- de un artículo, con su cantidad y costo unitario.
--
-- journal_entry_id es OPCIONAL (permite NULL): conecta el
-- movimiento físico con el asiento monetario que lo originó,
-- para trazabilidad, pero no todo movimiento de Kardex tiene
-- por qué generar un asiento propio en el sistema periódico
-- (por ejemplo, la venta sí afecta el Kardex al instante, pero
-- el asiento contable de esa venta solo toca la cuenta Ventas,
-- no Inventarios).
--
-- remaining_quantity: solo se usa si company.inventory_costing_method
-- = 'FIFO'. Guarda cuánto queda sin consumir de ESTA entrada
-- específica (una "capa" o lote). Para AVERAGE se deja NULL,
-- porque ese método no necesita distinguir lotes.
-- ============================================================

CREATE TABLE inventory_movement (
    id                  NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         CONSTRAINT pk_inventory_movement PRIMARY KEY,
    company_id          NUMBER          NOT NULL
                                         CONSTRAINT fk_movement_company
                                         REFERENCES company(id),
    item_id             NUMBER          NOT NULL
                                         CONSTRAINT fk_movement_item
                                         REFERENCES inventory_item(id),
    journal_entry_id    NUMBER
                                         CONSTRAINT fk_movement_entry
                                         REFERENCES journal_entry(id),
    movement_date       DATE            NOT NULL,
    movement_type       VARCHAR2(20)    NOT NULL
                                         CONSTRAINT ck_movement_type
                                         CHECK (movement_type IN ('OPENING_BALANCE','PURCHASE','SALE',
                                                                   'PURCHASE_RETURN','SALES_RETURN','CLOSING_BALANCE')),
    quantity            NUMBER(14,2)    NOT NULL
                                         CONSTRAINT ck_movement_quantity CHECK (quantity > 0),
    unit_cost           NUMBER(14,4)    NOT NULL
                                         CONSTRAINT ck_movement_unit_cost CHECK (unit_cost >= 0),
    remaining_quantity  NUMBER(14,2),   -- solo aplica bajo costeo FIFO, ver comentario arriba
    description         VARCHAR2(300)
);

COMMENT ON TABLE inventory_movement IS 'Kardex: movimientos perpetuos de entrada/salida física por artículo';
COMMENT ON COLUMN inventory_movement.movement_type IS
    'PURCHASE/SALE=compra o venta normal, PURCHASE_RETURN/SALES_RETURN=devoluciones, OPENING/CLOSING_BALANCE=apertura y cierre de ejercicio';
COMMENT ON COLUMN inventory_movement.remaining_quantity IS
    'Solo usado si company.inventory_costing_method = FIFO: cantidad no consumida de esta entrada (lote)';
