-- ============================================================
-- 18_permission.sql
-- Sin dependencias.
-- Catálogo de permisos individuales del sistema. Se asignan a
-- ROLES (no directo a usuarios), ver role_permission (19).
-- ============================================================

CREATE TABLE permission (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_permission PRIMARY KEY,
    code            VARCHAR2(40)    NOT NULL
                                     CONSTRAINT uq_permission_code UNIQUE,
    name            VARCHAR2(100)   NOT NULL,
    description     VARCHAR2(200)
);

COMMENT ON TABLE permission IS 'Catálogo de permisos individuales del sistema, asignados a roles';

-- Permisos base, según los módulos que ya venimos armando.
-- Esto es un punto de partida razonable, no una lista definitiva --
-- se pueden agregar más a medida que se arman las pantallas de APEX.
INSERT INTO permission (code, name, description) VALUES
    ('POST_JOURNAL_ENTRY', 'Contabilizar asientos', 'Crear y postear asientos contables');
INSERT INTO permission (code, name, description) VALUES
    ('REVERSE_JOURNAL_ENTRY', 'Anular asientos', 'Revertir asientos ya posteados');
INSERT INTO permission (code, name, description) VALUES
    ('CLOSE_PERIOD', 'Cerrar ejercicio', 'Ejecutar el proceso de cierre de un período contable');
INSERT INTO permission (code, name, description) VALUES
    ('MANAGE_CHART_OF_ACCOUNTS', 'Administrar catálogo', 'Crear/editar cuentas del catálogo contable');
INSERT INTO permission (code, name, description) VALUES
    ('MANAGE_USERS', 'Administrar usuarios', 'Crear usuarios, asignar roles y permisos');
INSERT INTO permission (code, name, description) VALUES
    ('VIEW_REPORTS', 'Ver reportes', 'Consultar balance general, estado de resultados y mayor');

COMMIT;
