-- ============================================================
-- 20_journal_entry_template.sql
-- Depende de: 01_company.sql
-- Encabezado de una plantilla de asiento recurrente
-- (ej. "Pago de planilla mensual", "Pago de alquiler").
-- ============================================================

CREATE TABLE journal_entry_template (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_entry_template PRIMARY KEY,
    company_id      NUMBER          NOT NULL
                                     CONSTRAINT fk_template_company
                                     REFERENCES company(id),
    code            VARCHAR2(30)    NOT NULL,
    name            VARCHAR2(150)   NOT NULL,
    description     VARCHAR2(300),
    entry_type      VARCHAR2(20)    DEFAULT 'MANUAL' NOT NULL
                                     CONSTRAINT ck_template_entry_type
                                     CHECK (entry_type IN ('MANUAL','OPENING','CLOSING','REVERSAL')),
    is_active       CHAR(1)         DEFAULT 'Y' NOT NULL
                                     CONSTRAINT ck_template_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT uq_template_company_code UNIQUE (company_id, code)
);

COMMENT ON TABLE journal_entry_template IS 'Plantillas de asientos recurrentes (encabezado)';
