-- ============================================================
-- 21_journal_entry_template_line.sql
-- Depende de: 20_journal_entry_template.sql, 06_gl_account.sql
--
-- Líneas de la plantilla. fixed_amount define si el monto de esa
-- línea es siempre el mismo (ej. una renta que nunca cambia) o
-- variable (fixed_amount = NULL, se pide al instanciar la plantilla).
--
-- LIMITACIÓN A PROPÓSITO: si una plantilla tiene MÁS DE UNA línea
-- variable, todas reciben el MISMO monto al instanciar (un solo
-- p_variable_amount por instanciación, ver pkg_entry_template).
-- Cubre el caso común (ej. Debe Gasto / Haber Banco, mismo monto
-- de los dos lados) pero no montos distintos por línea variable.
-- ============================================================

CREATE TABLE journal_entry_template_line (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_template_line PRIMARY KEY,
    template_id     NUMBER          NOT NULL
                                     CONSTRAINT fk_template_line_template
                                     REFERENCES journal_entry_template(id),
    account_id      NUMBER          NOT NULL
                                     CONSTRAINT fk_template_line_account
                                     REFERENCES gl_account(id),
    movement_type   CHAR(1)         NOT NULL
                                     CONSTRAINT ck_template_line_movement
                                     CHECK (movement_type IN ('D','C')),
    fixed_amount    NUMBER(14,2),   -- NULL = monto variable, se pide al instanciar
    description     VARCHAR2(300)
);

COMMENT ON TABLE journal_entry_template_line IS 'Líneas de una plantilla de asiento';
COMMENT ON COLUMN journal_entry_template_line.fixed_amount IS 'NULL = línea de monto variable (se completa al instanciar la plantilla)';
