-- ============================================================
-- 02_accounting_period.sql
-- Depende de: 01_company.sql
-- Cada empresa tiene sus propios períodos (ejercicios) contables.
-- El status controla si se puede seguir contabilizando en él.
-- ============================================================

CREATE TABLE accounting_period (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_accounting_period PRIMARY KEY,
    company_id      NUMBER          NOT NULL
                                     CONSTRAINT fk_period_company
                                     REFERENCES company(id),
    name            VARCHAR2(50)    NOT NULL,   -- ej. 'Ejercicio 2026'
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    status          VARCHAR2(10)    DEFAULT 'OPEN' NOT NULL
                                     CONSTRAINT ck_period_status
                                     CHECK (status IN ('OPEN','CLOSED')),
    closed_at       DATE,           -- se llena cuando status pasa a CLOSED
    CONSTRAINT ck_period_dates CHECK (end_date > start_date),
    CONSTRAINT uq_period_company_dates UNIQUE (company_id, start_date, end_date)
);

COMMENT ON TABLE accounting_period IS 'Ejercicios/períodos contables de cada empresa';
COMMENT ON COLUMN accounting_period.status IS 'OPEN permite contabilizar, CLOSED lo bloquea';
