-- ============================================================
-- 03_role.sql
-- Sin dependencias.
-- Un usuario puede tener VARIOS roles (ver 05_user_role.sql):
-- por ejemplo, un administrador también puede tener el rol de
-- contador para ver/operar como uno más cuando lo necesite.
-- ============================================================

CREATE TABLE role (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_role PRIMARY KEY,
    code            VARCHAR2(20)    NOT NULL
                                     CONSTRAINT uq_role_code UNIQUE,
    name            VARCHAR2(50)    NOT NULL,
    description     VARCHAR2(200)
);

COMMENT ON TABLE role IS 'Roles de acceso al sistema (un usuario puede tener varios, ver user_role)';

-- Datos base: los tres roles que definimos en la conversación.
-- ADMIN_EMPRESA: configura empresa, catálogo, cierra ejercicios
-- CONTADOR: registra y consulta asientos, no puede cerrar ejercicio
-- CONSULTA: solo lectura, para reportes y auditoría
INSERT INTO role (code, name, description) VALUES
    ('ADMIN_EMPRESA', 'Administrador de empresa', 'Configura empresa, catálogo y cierra ejercicios');
INSERT INTO role (code, name, description) VALUES
    ('CONTADOR', 'Contador operativo', 'Registra y consulta asientos contables');
INSERT INTO role (code, name, description) VALUES
    ('CONSULTA', 'Solo consulta', 'Acceso de solo lectura a reportes y mayor');

COMMIT;
