-- ============================================================
-- 04_user_account.sql
-- Depende de: 01_company.sql
-- Usuarios finales del sistema (NO son cuentas de workspace APEX).
-- Se llama USER_ACCOUNT y no USER porque USER es palabra reservada
-- en Oracle. Cada usuario pertenece a UNA sola empresa fija.
-- Los roles NO van acá: van en la tabla intermedia user_role (05),
-- porque un usuario puede tener más de uno.
-- ============================================================

CREATE TABLE user_account (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_user_account PRIMARY KEY,
    company_id      NUMBER          NOT NULL
                                     CONSTRAINT fk_user_company
                                     REFERENCES company(id),
    username        VARCHAR2(50)    NOT NULL
                                     CONSTRAINT uq_user_username UNIQUE,
    full_name       VARCHAR2(150)   NOT NULL,
    email           VARCHAR2(150),
    -- El hash y la sal se calculan en la función de autenticación
    -- que armamos cuando lleguemos al esquema de auth de APEX.
    password_hash   VARCHAR2(64)    NOT NULL,  -- SHA-256 en hexadecimal = 64 caracteres
    password_salt   VARCHAR2(32)    NOT NULL,
    is_active       CHAR(1)         DEFAULT 'Y' NOT NULL
                                     CONSTRAINT ck_user_active CHECK (is_active IN ('Y','N')),
    created_at      DATE            DEFAULT SYSDATE NOT NULL,
    last_login_at   DATE
);

COMMENT ON TABLE user_account IS 'Usuarios finales de la aplicación (login propio, no cuentas de workspace)';
COMMENT ON COLUMN user_account.password_hash IS 'SHA-256 de (password + salt), ver función de autenticación en APEX';
