-- ============================================================
-- 07_journal_entry.sql
-- Depende de: 01_company.sql, 02_accounting_period.sql, 04_user_account.sql
-- Encabezado del asiento (libro diario). El detalle (líneas
-- debe/haber) va en journal_entry_line (08). El número correlativo
-- lo asigna el paquete PL/SQL al postear (no es una IDENTITY),
-- porque tiene que ser correlativo POR EMPRESA, sin saltos.
-- ============================================================

CREATE TABLE journal_entry (
    id                  NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         CONSTRAINT pk_journal_entry PRIMARY KEY,
    company_id          NUMBER          NOT NULL
                                         CONSTRAINT fk_entry_company
                                         REFERENCES company(id),
    period_id           NUMBER          NOT NULL
                                         CONSTRAINT fk_entry_period
                                         REFERENCES accounting_period(id),
    entry_number        NUMBER          NOT NULL,  -- asignado por el paquete, correlativo por empresa
    entry_date          DATE            NOT NULL,
    description          VARCHAR2(500)   NOT NULL,
    entry_type          VARCHAR2(20)    DEFAULT 'MANUAL' NOT NULL
                                         CONSTRAINT ck_entry_type
                                         CHECK (entry_type IN ('MANUAL','OPENING','CLOSING','REVERSAL')),
    status              VARCHAR2(15)    DEFAULT 'ACTIVE' NOT NULL
                                         CONSTRAINT ck_entry_status
                                         CHECK (status IN ('ACTIVE','REVERSED')),
    created_by          NUMBER          NOT NULL
                                         CONSTRAINT fk_entry_user
                                         REFERENCES user_account(id),
    created_at          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_entry_company_number UNIQUE (company_id, entry_number)
);

COMMENT ON TABLE journal_entry IS 'Encabezado de asientos contables (libro diario)';
COMMENT ON COLUMN journal_entry.entry_number IS 'Correlativo por empresa, asignado por PKG_JOURNAL_ENTRY al postear';
COMMENT ON COLUMN journal_entry.entry_type IS 'MANUAL=registrado a mano, OPENING/CLOSING=generados por el sistema, REVERSAL=anula otro asiento';
