-- ============================================================
-- 13_inventory_item.sql
-- Depende de: 01_company.sql
-- Catálogo de artículos/productos físicos que se compran y venden.
-- Es el "maestro" sobre el que corre el Kardex.
-- ============================================================

CREATE TABLE inventory_item (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     CONSTRAINT pk_inventory_item PRIMARY KEY,
    company_id      NUMBER          NOT NULL
                                     CONSTRAINT fk_item_company
                                     REFERENCES company(id),
    code            VARCHAR2(30)    NOT NULL,
    name            VARCHAR2(150)   NOT NULL,
    unit_of_measure VARCHAR2(20)    NOT NULL,   -- ej. 'unidad', 'caja', 'kg'
    is_active       CHAR(1)         DEFAULT 'Y' NOT NULL
                                     CONSTRAINT ck_item_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT uq_item_company_code UNIQUE (company_id, code)
);

COMMENT ON TABLE inventory_item IS 'Catálogo de artículos físicos (productos) por empresa, base del Kardex';
